import 'package:flutter/material.dart';
import 'package:flutterapp/projetowinehuntapp/generatedpagamentocreditowidget/generated/GeneratedEllipse10Widget.dart';
import 'package:flutterapp/projetowinehuntapp/generatedpagamentocreditowidget/generated/GeneratedVectorWidget133.dart';
import 'package:flutterapp/projetowinehuntapp/generatedpagamentocreditowidget/generated/GeneratedCadastrarWidget6.dart';
import 'package:flutterapp/projetowinehuntapp/generatedpagamentocreditowidget/generated/GeneratedArrow_backWidget9.dart';
import 'package:flutterapp/projetowinehuntapp/generatedpagamentocreditowidget/generated/GeneratedRectangle39Widget.dart';
import 'package:flutterapp/projetowinehuntapp/generatedpagamentocreditowidget/generated/GeneratedIOSWidget9.dart';
import 'package:flutterapp/projetowinehuntapp/generatedpagamentocreditowidget/generated/GeneratedComponent1Widget1.dart';
import 'package:flutterapp/projetowinehuntapp/generatedpagamentocreditowidget/generated/GeneratedRectangle31Widget1.dart';
import 'package:flutterapp/projetowinehuntapp/generatedpagamentocreditowidget/generated/GeneratedCartodecrditoWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';

/* Component pagamento credito
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedPagamentocreditoWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 736.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(127, 230, 58, 58),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 136.0,
                right: null,
                bottom: null,
                width: 413.0,
                height: 72.0,
                child: GeneratedRectangle31Widget1(),
              ),
              Positioned(
                left: 1.0,
                top: 76.0,
                right: null,
                bottom: null,
                width: 413.0,
                height: 37.0,
                child: GeneratedComponent1Widget1(),
              ),
              Positioned(
                left: 246.0,
                top: 629.0,
                right: null,
                bottom: null,
                width: 143.0,
                height: 42.0,
                child: GeneratedCadastrarWidget6(),
              ),
              Positioned(
                left: 1.0,
                top: 228.0,
                right: null,
                bottom: null,
                width: 413.0,
                height: 356.0,
                child: GeneratedRectangle39Widget(),
              ),
              Positioned(
                left: 7.0,
                top: 36.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedArrow_backWidget9(),
              ),
              Positioned(
                left: 1.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 411.0,
                height: 21.0,
                child: GeneratedIOSWidget9(),
              ),
              Positioned(
                left: 35.0,
                top: 142.0,
                right: null,
                bottom: null,
                width: 61.0,
                height: 61.0,
                child: GeneratedEllipse10Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.10869566138815764;
                  double scaleX = (constraints.maxWidth * percentWidth) /
                      45.000003814697266;

                  double percentHeight = 0.043478260869565216;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 32.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.10386473429951691,
                        translateY: constraints.maxHeight * 0.21195652173913043,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedVectorWidget133())
                  ]);
                }),
              ),
              Positioned(
                left: 112.0,
                top: 155.0,
                right: null,
                bottom: null,
                width: 289.0,
                height: 41.0,
                child: GeneratedCartodecrditoWidget(),
              )
            ]),
      ),
    ));
  }
}
