import 'package:flutter/material.dart';
import 'package:flutterapp/projetowinehuntapp/generatedframe7widget/generated/GeneratedProduto1Widget2.dart';
import 'package:flutterapp/projetowinehuntapp/generatedframe7widget/generated/GeneratedShopping_cartWidget4.dart';

/* Frame Frame 7
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFrame7Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 413.0,
        height: 736.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 413.0,
                height: 1420.0,
                child: GeneratedProduto1Widget2(),
              ),
              Positioned(
                left: 358.0,
                top: 47.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedShopping_cartWidget4(),
              )
            ]),
      ),
    ));
  }
}
