import 'package:flutter/material.dart';
import 'package:flutterapp/projetowinehuntapp/generatedcadastrodecartowidget/generated/GeneratedLine1Widget.dart';
import 'package:flutterapp/projetowinehuntapp/generatedcadastrodecartowidget/generated/GeneratedComponent1Widget.dart';
import 'package:flutterapp/projetowinehuntapp/generatedcadastrodecartowidget/generated/GeneratedLine5Widget.dart';
import 'package:flutterapp/projetowinehuntapp/generatedcadastrodecartowidget/generated/GeneratedDatadevencimentoWidget.dart';
import 'package:flutterapp/projetowinehuntapp/generatedcadastrodecartowidget/generated/GeneratedRectangle38Widget.dart';
import 'package:flutterapp/projetowinehuntapp/generatedcadastrodecartowidget/generated/GeneratedLine3Widget.dart';
import 'package:flutterapp/projetowinehuntapp/generatedcadastrodecartowidget/generated/GeneratedNmerodocartoWidget.dart';
import 'package:flutterapp/projetowinehuntapp/generatedcadastrodecartowidget/generated/GeneratedIOSWidget8.dart';
import 'package:flutterapp/projetowinehuntapp/generatedcadastrodecartowidget/generated/GeneratedLine2Widget.dart';
import 'package:flutterapp/projetowinehuntapp/generatedcadastrodecartowidget/generated/GeneratedCdigodeseguranaWidget.dart';
import 'package:flutterapp/projetowinehuntapp/generatedcadastrodecartowidget/generated/GeneratedCadastrarWidget3.dart';
import 'package:flutterapp/projetowinehuntapp/generatedcadastrodecartowidget/generated/GeneratedLine4Widget.dart';
import 'package:flutterapp/projetowinehuntapp/generatedcadastrodecartowidget/generated/GeneratedCPFdottutardocartoWidget.dart';
import 'package:flutterapp/projetowinehuntapp/generatedcadastrodecartowidget/generated/GeneratedNomecompletoWidget.dart';
import 'package:flutterapp/projetowinehuntapp/generatedcadastrodecartowidget/generated/GeneratedArrow_backWidget8.dart';

/* Frame Cadastro de cartão
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCadastrodecartoWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 736.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(127, 230, 58, 58),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 204.0,
                right: null,
                bottom: null,
                width: 413.0,
                height: 396.0,
                child: GeneratedRectangle38Widget(),
              ),
              Positioned(
                left: 7.0,
                top: 281.0,
                right: null,
                bottom: null,
                width: 270.0018615722656,
                height: 1.0,
                child: GeneratedLine1Widget(),
              ),
              Positioned(
                left: 8.0,
                top: 556.0,
                right: null,
                bottom: null,
                width: 270.0,
                height: 1.0,
                child: GeneratedLine3Widget(),
              ),
              Positioned(
                left: 7.0,
                top: 354.0,
                right: null,
                bottom: null,
                width: 338.00146484375,
                height: 1.0,
                child: GeneratedLine2Widget(),
              ),
              Positioned(
                left: 7.0,
                top: 495.0,
                right: null,
                bottom: null,
                width: 169.00296020507812,
                height: 1.0,
                child: GeneratedLine5Widget(),
              ),
              Positioned(
                left: 8.0,
                top: 425.0,
                right: null,
                bottom: null,
                width: 168.0029754638672,
                height: 1.0,
                child: GeneratedLine4Widget(),
              ),
              Positioned(
                left: 11.0,
                top: 236.0,
                right: null,
                bottom: null,
                width: 247.0,
                height: 16.0,
                child: GeneratedNmerodocartoWidget(),
              ),
              Positioned(
                left: 11.0,
                top: 515.0,
                right: null,
                bottom: null,
                width: 247.0,
                height: 16.0,
                child: GeneratedCPFdottutardocartoWidget(),
              ),
              Positioned(
                left: 11.0,
                top: 454.0,
                right: null,
                bottom: null,
                width: 247.0,
                height: 16.0,
                child: GeneratedCdigodeseguranaWidget(),
              ),
              Positioned(
                left: 11.0,
                top: 381.0,
                right: null,
                bottom: null,
                width: 247.0,
                height: 16.0,
                child: GeneratedDatadevencimentoWidget(),
              ),
              Positioned(
                left: 7.0,
                top: 310.0,
                right: null,
                bottom: null,
                width: 247.0,
                height: 16.0,
                child: GeneratedNomecompletoWidget(),
              ),
              Positioned(
                left: 238.0,
                top: 634.0,
                right: null,
                bottom: null,
                width: 143.0,
                height: 42.0,
                child: GeneratedCadastrarWidget3(),
              ),
              Positioned(
                left: 2.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 411.0,
                height: 21.0,
                child: GeneratedIOSWidget8(),
              ),
              Positioned(
                left: 1.0,
                top: 47.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedArrow_backWidget8(),
              ),
              Positioned(
                left: 0.0,
                top: 89.0,
                right: null,
                bottom: null,
                width: 413.0,
                height: 37.0,
                child: GeneratedComponent1Widget(),
              )
            ]),
      ),
    ));
  }
}
