import 'package:flutter/material.dart';
import 'package:flutterapp/projetowinehuntapp/generatedcarrinhodecompraswidget/generated/GeneratedAddWidget.dart';
import 'package:flutterapp/projetowinehuntapp/generatedcarrinhodecompraswidget/generated/GeneratedR\$259999Widget.dart';
import 'package:flutterapp/projetowinehuntapp/generatedcarrinhodecompraswidget/generated/GeneratedRectangle27Widget.dart';
import 'package:flutterapp/projetowinehuntapp/generatedcarrinhodecompraswidget/generated/GeneratedRectangle25Widget.dart';
import 'package:flutterapp/projetowinehuntapp/generatedcarrinhodecompraswidget/generated/GeneratedSEUCARRINHOWidget.dart';
import 'package:flutterapp/projetowinehuntapp/generatedcarrinhodecompraswidget/generated/GeneratedRectangle26Widget.dart';
import 'package:flutterapp/projetowinehuntapp/generatedcarrinhodecompraswidget/generated/GeneratedEscolheraformadepagamentoWidget.dart';
import 'package:flutterapp/projetowinehuntapp/generatedcarrinhodecompraswidget/generated/GeneratedCasaValduga1875VinhoLicoroso375mlWidget.dart';
import 'package:flutterapp/projetowinehuntapp/generatedcarrinhodecompraswidget/generated/GeneratedShopping_cartWidget3.dart';
import 'package:flutterapp/projetowinehuntapp/generatedcarrinhodecompraswidget/generated/Generated1Widget.dart';
import 'package:flutterapp/projetowinehuntapp/generatedcarrinhodecompraswidget/generated/GeneratedRectangle28Widget.dart';
import 'package:flutterapp/projetowinehuntapp/generatedcarrinhodecompraswidget/generated/GeneratedRemoveWidget.dart';
import 'package:flutterapp/projetowinehuntapp/generatedcarrinhodecompraswidget/generated/GeneratedCloseWidget.dart';
import 'package:flutterapp/projetowinehuntapp/generatedcarrinhodecompraswidget/generated/GeneratedArrow_backWidget5.dart';
import 'package:flutterapp/projetowinehuntapp/generatedcarrinhodecompraswidget/generated/GeneratedIOSWidget5.dart';

/* Frame Carrinho de compras
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedCarrinhodecomprasWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 413.0,
        height: 736.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(127, 230, 58, 58),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 42.0,
                right: null,
                bottom: null,
                width: 30.0,
                height: 24.0,
                child: GeneratedArrow_backWidget5(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 411.0,
                height: 21.0,
                child: GeneratedIOSWidget5(),
              ),
              Positioned(
                left: 0.0,
                top: 601.0,
                right: null,
                bottom: null,
                width: 411.0,
                height: 55.0,
                child: GeneratedRectangle25Widget(),
              ),
              Positioned(
                left: 5.0,
                top: 601.0,
                right: null,
                bottom: null,
                width: 408.0,
                height: 57.0,
                child: GeneratedEscolheraformadepagamentoWidget(),
              ),
              Positioned(
                left: 48.0,
                top: 38.0,
                right: null,
                bottom: null,
                width: 333.0,
                height: 45.0,
                child: GeneratedSEUCARRINHOWidget(),
              ),
              Positioned(
                left: 106.0,
                top: 46.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedShopping_cartWidget3(),
              ),
              Positioned(
                left: 0.0,
                top: 111.0,
                right: null,
                bottom: null,
                width: 411.0,
                height: 185.0,
                child: GeneratedRectangle26Widget(),
              ),
              Positioned(
                left: 15.0,
                top: 115.0,
                right: null,
                bottom: null,
                width: 124.0,
                height: 172.0,
                child: GeneratedRectangle27Widget(),
              ),
              Positioned(
                left: 363.0,
                top: 134.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedCloseWidget(),
              ),
              Positioned(
                left: 147.0,
                top: 131.0,
                right: null,
                bottom: null,
                width: 206.0,
                height: 40.0,
                child: GeneratedCasaValduga1875VinhoLicoroso375mlWidget(),
              ),
              Positioned(
                left: 151.0,
                top: 248.0,
                right: null,
                bottom: null,
                width: 115.0,
                height: 41.0,
                child: GeneratedR$259999Widget(),
              ),
              Positioned(
                left: 297.0,
                top: 238.0,
                right: null,
                bottom: null,
                width: 96.0,
                height: 40.0,
                child: GeneratedRectangle28Widget(),
              ),
              Positioned(
                left: 297.0,
                top: 248.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedRemoveWidget(),
              ),
              Positioned(
                left: 367.0,
                top: 249.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedAddWidget(),
              ),
              Positioned(
                left: 321.0,
                top: 238.0,
                right: null,
                bottom: null,
                width: 51.0,
                height: 45.0,
                child: Generated1Widget(),
              )
            ]),
      ),
    ));
  }
}
