import 'package:flutter/material.dart';
import 'package:flutterapp/projetowinehuntapp/generatedframe5widget/generated/GeneratedShopping_cartWidget1.dart';
import 'package:flutterapp/projetowinehuntapp/generatedframe5widget/generated/GeneratedProduto1Widget.dart';

/* Frame Frame 5
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFrame5Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Container(
              width: 417.0,
              height: 736.0,
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 413.0,
              height: 1439.0,
              child: GeneratedProduto1Widget(),
            ),
            Positioned(
              left: 364.0,
              top: 49.0,
              right: null,
              bottom: null,
              width: 24.0,
              height: 24.0,
              child: GeneratedShopping_cartWidget1(),
            )
          ]),
    ));
  }
}
