import 'package:flutter/material.dart';
import 'package:flutterapp/projetowinehuntapp/generateddeuteranomalyvisionwidget/generated/GeneratedArrow_backWidget10.dart';

/* Group Deuteranomaly vision
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedDeuteranomalyvisionWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 24.0,
      height: 24.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 24.0,
              height: 24.0,
              child: GeneratedArrow_backWidget10(),
            )
          ]),
    ));
  }
}
