import 'package:flutter/material.dart';
import 'package:flutterapp/projetowinehuntapp/generatedmainwidget/generated/GeneratedVectorWidget27.dart';
import 'package:flutterapp/projetowinehuntapp/generatedmainwidget/generated/GeneratedArrow_backWidget.dart';
import 'package:flutterapp/projetowinehuntapp/generatedmainwidget/generated/GeneratedGroup4Widget.dart';
import 'package:flutterapp/projetowinehuntapp/generatedmainwidget/generated/GeneratedReceiptWidget.dart';
import 'package:flutterapp/projetowinehuntapp/generatedmainwidget/generated/GeneratedEllipse4Widget.dart';
import 'package:flutterapp/projetowinehuntapp/generatedmainwidget/generated/GeneratedHomeWidget.dart';
import 'package:flutterapp/projetowinehuntapp/generatedmainwidget/generated/GeneratedShopping_cartWidget.dart';
import 'package:flutterapp/projetowinehuntapp/generatedmainwidget/generated/GeneratedUnionWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/projetowinehuntapp/generatedmainwidget/generated/GeneratedRectangle14Widget.dart';
import 'package:flutterapp/projetowinehuntapp/generatedmainwidget/generated/GeneratedIOSWidget.dart';
import 'package:flutterapp/projetowinehuntapp/generatedmainwidget/generated/GeneratedSearchWidget1.dart';
import 'package:flutterapp/projetowinehuntapp/generatedmainwidget/generated/GeneratedRectangle12Widget.dart';
import 'package:flutterapp/projetowinehuntapp/generatedmainwidget/generated/GeneratedReorderWidget.dart';
import 'package:flutterapp/projetowinehuntapp/generatedmainwidget/generated/GeneratedCupomWidget.dart';
import 'package:flutterapp/projetowinehuntapp/generatedmainwidget/generated/GeneratedGroup5Widget.dart';
import 'package:flutterapp/projetowinehuntapp/generatedmainwidget/generated/GeneratedLojaWidget.dart';
import 'package:flutterapp/projetowinehuntapp/generatedmainwidget/generated/GeneratedRectangle8Widget.dart';
import 'package:flutterapp/projetowinehuntapp/generatedmainwidget/generated/GeneratedGroup3Widget.dart';
import 'package:flutterapp/projetowinehuntapp/generatedmainwidget/generated/GeneratedRectangle3Widget2.dart';
import 'package:flutterapp/projetowinehuntapp/generatedmainwidget/generated/GeneratedSearchWidget.dart';

/* Frame Main 
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedMainWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Container(
              width: 414.0,
              height: 736.0,
              child: Stack(
                  fit: StackFit.expand,
                  alignment: Alignment.center,
                  overflow: Overflow.visible,
                  children: [
                    ClipRRect(
                      borderRadius: BorderRadius.zero,
                      child: Container(
                        color: Color.fromARGB(255, 255, 255, 255),
                      ),
                    ),
                    Positioned(
                      left: 1.0,
                      top: 0.0,
                      right: null,
                      bottom: null,
                      width: 411.0,
                      height: 21.0,
                      child: GeneratedIOSWidget(),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: 0.0,
                      bottom: 0.0,
                      width: null,
                      height: null,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        double percentWidth = 0.025845419381551698;
                        double scaleX = (constraints.maxWidth * percentWidth) /
                            10.700003623962402;

                        double percentHeight = 0.012039842812911324;
                        double scaleY =
                            (constraints.maxHeight * percentHeight) /
                                8.861324310302734;

                        return Stack(children: [
                          TransformHelper.translateAndScale(
                              translateX:
                                  constraints.maxWidth * 1.0458937198067633,
                              translateY:
                                  constraints.maxHeight * 0.5258942894313646,
                              translateZ: 0,
                              scaleX: scaleX,
                              scaleY: scaleY,
                              scaleZ: 1,
                              child: GeneratedUnionWidget())
                        ]);
                      }),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 685.0,
                      right: null,
                      bottom: null,
                      width: 418.0,
                      height: 57.0,
                      child: GeneratedRectangle12Widget(),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 696.0,
                      right: null,
                      bottom: null,
                      width: 139.0,
                      height: 40.0,
                      child: GeneratedRectangle14Widget(),
                    ),
                    Positioned(
                      left: 45.0,
                      top: 711.0,
                      right: null,
                      bottom: null,
                      width: 51.0,
                      height: 21.0,
                      child: GeneratedHomeWidget(),
                    ),
                    Positioned(
                      left: 61.0,
                      top: 693.0,
                      right: null,
                      bottom: null,
                      width: 328.0,
                      height: 35.0,
                      child: GeneratedGroup4Widget(),
                    ),
                    Positioned(
                      left: 146.0,
                      top: 422.0,
                      right: null,
                      bottom: null,
                      width: 24.0,
                      height: 24.0,
                      child: GeneratedSearchWidget(),
                    ),
                    Positioned(
                      left: 12.0,
                      top: 272.0,
                      right: null,
                      bottom: null,
                      width: 24.0,
                      height: 24.0,
                      child: GeneratedGroup5Widget(),
                    ),
                    Positioned(
                      left: 7.0,
                      top: 317.0,
                      right: null,
                      bottom: null,
                      width: 97.0,
                      height: 28.0,
                      child: GeneratedCupomWidget(),
                    ),
                    Positioned(
                      left: 4.0,
                      top: 87.0,
                      right: null,
                      bottom: null,
                      width: 399.0,
                      height: 38.0,
                      child: GeneratedRectangle3Widget2(),
                    ),
                    Positioned(
                      left: 277.0,
                      top: 186.0,
                      right: null,
                      bottom: null,
                      width: 55.0,
                      height: 47.0,
                      child: GeneratedEllipse4Widget(),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 0.0,
                      right: 0.0,
                      bottom: 0.0,
                      width: null,
                      height: null,
                      child: LayoutBuilder(builder:
                          (BuildContext context, BoxConstraints constraints) {
                        double percentWidth = 0.07729468599033816;
                        double scaleX =
                            (constraints.maxWidth * percentWidth) / 32.0;

                        double percentHeight = 0.043478260869565216;
                        double scaleY =
                            (constraints.maxHeight * percentHeight) / 32.0;

                        return Stack(children: [
                          TransformHelper.translateAndScale(
                              translateX:
                                  constraints.maxWidth * 0.7753623188405797,
                              translateY:
                                  constraints.maxHeight * 0.264945652173913,
                              translateZ: 0,
                              scaleX: scaleX,
                              scaleY: scaleY,
                              scaleZ: 1,
                              child: GeneratedVectorWidget27())
                        ]);
                      }),
                    )
                  ]),
            ),
            Positioned(
              left: 14.0,
              top: 274.0,
              right: null,
              bottom: null,
              width: 85.0,
              height: 22.0,
              child: GeneratedLojaWidget(),
            ),
            Positioned(
              left: 4.0,
              top: 51.0,
              right: null,
              bottom: null,
              width: 24.0,
              height: 24.0,
              child: GeneratedArrow_backWidget(),
            ),
            Positioned(
              left: 382.0,
              top: 54.0,
              right: null,
              bottom: null,
              width: 24.0,
              height: 24.0,
              child: GeneratedReorderWidget(),
            ),
            Positioned(
              left: 4.0,
              top: 181.0,
              right: null,
              bottom: null,
              width: 393.0,
              height: 70.0,
              child: GeneratedRectangle8Widget(),
            ),
            Positioned(
              left: 330.0,
              top: 204.0,
              right: null,
              bottom: null,
              width: 41.0,
              height: 19.0,
              child: GeneratedShopping_cartWidget(),
            ),
            Positioned(
              left: 95.0,
              top: 235.0,
              right: null,
              bottom: null,
              width: 233.0,
              height: 9.0,
              child: GeneratedGroup3Widget(),
            ),
            Positioned(
              left: 12.0,
              top: 317.0,
              right: null,
              bottom: null,
              width: 24.0,
              height: 24.0,
              child: GeneratedReceiptWidget(),
            ),
            Positioned(
              left: 8.0,
              top: 93.0,
              right: null,
              bottom: null,
              width: 24.0,
              height: 24.0,
              child: GeneratedSearchWidget1(),
            )
          ]),
    ));
  }
}
