import 'package:flutter/material.dart';
import 'package:flutterapp/projetowinehuntapp/generatedhomewidget2/generated/GeneratedArrow_backWidget1.dart';
import 'package:flutterapp/projetowinehuntapp/generatedhomewidget2/generated/GeneratedRectangle15Widget.dart';
import 'package:flutterapp/projetowinehuntapp/generatedhomewidget2/generated/GeneratedReorderWidget1.dart';
import 'package:flutterapp/projetowinehuntapp/generatedhomewidget2/generated/GeneratedRectangle22Widget.dart';
import 'package:flutterapp/projetowinehuntapp/generatedhomewidget2/generated/GeneratedIOSWidget1.dart';
import 'package:flutterapp/projetowinehuntapp/generatedhomewidget2/generated/GeneratedFrame2Widget.dart';
import 'package:flutterapp/projetowinehuntapp/generatedhomewidget2/generated/GeneratedAdd_shopping_cartWidget.dart';
import 'package:flutterapp/projetowinehuntapp/generatedhomewidget2/generated/GeneratedPlaceWidget.dart';
import 'package:flutterapp/projetowinehuntapp/generatedhomewidget2/generated/GeneratedSearchWidget2.dart';
import 'package:flutterapp/projetowinehuntapp/generatedhomewidget2/generated/GeneratedLocal_mallWidget1.dart';
import 'package:flutterapp/projetowinehuntapp/generatedhomewidget2/generated/GeneratedFrame3Widget.dart';
import 'package:flutterapp/projetowinehuntapp/generatedhomewidget2/generated/GeneratedLocal_atmWidget.dart';
import 'package:flutterapp/projetowinehuntapp/generatedhomewidget2/generated/GeneratedRectangle8Widget2.dart';

/* Frame Home
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHomeWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Container(
              width: 415.0,
              height: 736.0,
              child: Stack(
                  fit: StackFit.expand,
                  alignment: Alignment.center,
                  overflow: Overflow.visible,
                  children: [
                    ClipRRect(
                      borderRadius: BorderRadius.zero,
                      child: Container(
                        color: Color.fromARGB(127, 230, 58, 58),
                      ),
                    ),
                    Positioned(
                      left: 0.0,
                      top: 426.0,
                      right: null,
                      bottom: null,
                      width: 416.0,
                      height: 206.0,
                      child: GeneratedRectangle22Widget(),
                    ),
                    Positioned(
                      left: 3.0,
                      top: 82.0,
                      right: null,
                      bottom: null,
                      width: 366.0,
                      height: 38.0,
                      child: GeneratedRectangle15Widget(),
                    ),
                    Positioned(
                      left: 383.0,
                      top: 46.0,
                      right: null,
                      bottom: null,
                      width: 24.0,
                      height: 24.0,
                      child: GeneratedReorderWidget1(),
                    )
                  ]),
            ),
            Positioned(
              left: -29.0,
              top: 661.0,
              right: null,
              bottom: null,
              width: 474.0,
              height: 75.0,
              child: GeneratedRectangle8Widget2(),
            ),
            Positioned(
              left: 4.0,
              top: 398.0,
              right: null,
              bottom: null,
              width: 408.0,
              height: 242.0,
              child: GeneratedFrame2Widget(),
            ),
            Positioned(
              left: 0.0,
              top: 164.0,
              right: null,
              bottom: null,
              width: 769.0,
              height: 226.0,
              child: GeneratedFrame3Widget(),
            ),
            Positioned(
              left: 0.0,
              top: 50.0,
              right: null,
              bottom: null,
              width: 24.0,
              height: 24.0,
              child: GeneratedArrow_backWidget1(),
            ),
            Positioned(
              left: 4.0,
              top: 3.0,
              right: null,
              bottom: null,
              width: 411.0,
              height: 21.0,
              child: GeneratedIOSWidget1(),
            ),
            Positioned(
              left: 379.0,
              top: 79.0,
              right: null,
              bottom: null,
              width: 51.0,
              height: 36.0,
              child: GeneratedAdd_shopping_cartWidget(),
            ),
            Positioned(
              left: 177.0,
              top: 671.0,
              right: null,
              bottom: null,
              width: 48.0,
              height: 48.0,
              child: GeneratedLocal_mallWidget1(),
            ),
            Positioned(
              left: 313.0,
              top: 671.0,
              right: null,
              bottom: null,
              width: 48.0,
              height: 48.0,
              child: GeneratedLocal_atmWidget(),
            ),
            Positioned(
              left: 41.0,
              top: 671.0,
              right: null,
              bottom: null,
              width: 48.0,
              height: 48.0,
              child: GeneratedPlaceWidget(),
            ),
            Positioned(
              left: 12.0,
              top: 88.0,
              right: null,
              bottom: null,
              width: 24.0,
              height: 24.0,
              child: GeneratedSearchWidget2(),
            )
          ]),
    ));
  }
}
