import 'package:flutter/material.dart';
import 'package:flutterapp/projetowinehuntapp/generatedformasdepagamentowidget/generated/GeneratedRectangle30Widget.dart';
import 'package:flutterapp/projetowinehuntapp/generatedformasdepagamentowidget/generated/GeneratedRectangle31Widget.dart';
import 'package:flutterapp/projetowinehuntapp/generatedformasdepagamentowidget/generated/GeneratedVectorWidget118.dart';
import 'package:flutterapp/projetowinehuntapp/generatedformasdepagamentowidget/generated/GeneratedVectorWidget113.dart';
import 'package:flutterapp/projetowinehuntapp/generatedformasdepagamentowidget/generated/GeneratedPIXWidget.dart';
import 'package:flutterapp/projetowinehuntapp/generatedformasdepagamentowidget/generated/GeneratedVectorWidget116.dart';
import 'package:flutterapp/projetowinehuntapp/generatedformasdepagamentowidget/generated/GeneratedRectangle29Widget.dart';
import 'package:flutterapp/projetowinehuntapp/generatedformasdepagamentowidget/generated/GeneratedEllipse6Widget.dart';
import 'package:flutterapp/projetowinehuntapp/generatedformasdepagamentowidget/generated/GeneratedFormadepagementoWidget.dart';
import 'package:flutterapp/projetowinehuntapp/generatedformasdepagamentowidget/generated/GeneratedVectorWidget110.dart';
import 'package:flutterapp/projetowinehuntapp/generatedformasdepagamentowidget/generated/GeneratedBoletoWidget.dart';
import 'package:flutterapp/projetowinehuntapp/generatedformasdepagamentowidget/generated/GeneratedRectangle35Widget.dart';
import 'package:flutterapp/projetowinehuntapp/generatedformasdepagamentowidget/generated/GeneratedNovocartoWidget.dart';
import 'package:flutterapp/projetowinehuntapp/generatedformasdepagamentowidget/generated/GeneratedVectorWidget109.dart';
import 'package:flutterapp/projetowinehuntapp/generatedformasdepagamentowidget/generated/GeneratedProduto1Widget3.dart';
import 'package:flutterapp/projetowinehuntapp/generatedformasdepagamentowidget/generated/GeneratedEllipse7Widget.dart';
import 'package:flutterapp/projetowinehuntapp/generatedformasdepagamentowidget/generated/GeneratedRectangle36Widget.dart';
import 'package:flutterapp/projetowinehuntapp/generatedformasdepagamentowidget/generated/GeneratedVectorWidget111.dart';
import 'package:flutterapp/projetowinehuntapp/generatedformasdepagamentowidget/generated/GeneratedOutrosmeiosdepagementoWidget.dart';
import 'package:flutterapp/projetowinehuntapp/generatedformasdepagamentowidget/generated/GeneratedCrditoWidget.dart';
import 'package:flutterapp/projetowinehuntapp/generatedformasdepagamentowidget/generated/GeneratedFrame8Widget.dart';
import 'package:flutterapp/projetowinehuntapp/generatedformasdepagamentowidget/generated/GeneratedEllipse9Widget.dart';
import 'package:flutterapp/projetowinehuntapp/generatedformasdepagamentowidget/generated/GeneratedEllipse8Widget.dart';
import 'package:flutterapp/projetowinehuntapp/generatedformasdepagamentowidget/generated/GeneratedVectorWidget112.dart';
import 'package:flutterapp/projetowinehuntapp/generatedformasdepagamentowidget/generated/GeneratedDbitoWidget.dart';
import 'package:flutterapp/projetowinehuntapp/generatedformasdepagamentowidget/generated/GeneratedEllipse5Widget.dart';
import 'package:flutterapp/projetowinehuntapp/generatedformasdepagamentowidget/generated/GeneratedVectorWidget117.dart';
import 'package:flutterapp/projetowinehuntapp/generatedformasdepagamentowidget/generated/GeneratedRectangle37Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/projetowinehuntapp/generatedformasdepagamentowidget/generated/GeneratedVectorWidget114.dart';

/* Component Formas de pagamento
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFormasdepagamentoWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 413.0,
      height: 736.0,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                final double width = constraints.maxWidth;

                final double height = constraints.maxHeight;

                return Stack(children: [
                  TransformHelper.translate(
                      x: 0,
                      y: 0,
                      z: 0,
                      child: Container(
                        width: width,
                        height: height,
                        child: GeneratedProduto1Widget3(),
                      ))
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 384.0,
              right: null,
              bottom: null,
              width: 413.0,
              height: 108.0,
              child: GeneratedRectangle35Widget(),
            ),
            Positioned(
              left: 0.0,
              top: 648.0,
              right: null,
              bottom: null,
              width: 413.0,
              height: 87.0,
              child: GeneratedRectangle37Widget(),
            ),
            Positioned(
              left: 0.0,
              top: 558.0,
              right: null,
              bottom: null,
              width: 413.0,
              height: 90.0,
              child: GeneratedRectangle36Widget(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                double percentWidth = 0.048426150121065374;
                double scaleX = (constraints.maxWidth * percentWidth) / 20.0;

                double percentHeight = 0.02717391304347826;
                double scaleY = (constraints.maxHeight * percentHeight) / 20.0;

                return Stack(children: [
                  TransformHelper.translateAndScale(
                      translateX: constraints.maxWidth * 0.0387409200968523,
                      translateY: constraints.maxHeight * 0.8057065217391305,
                      translateZ: 0,
                      scaleX: scaleX,
                      scaleY: scaleY,
                      scaleZ: 1,
                      child: GeneratedVectorWidget109())
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                double percentWidth = 0.048426150121065374;
                double scaleX = (constraints.maxWidth * percentWidth) / 20.0;

                double percentHeight = 0.02717391304347826;
                double scaleY = (constraints.maxHeight * percentHeight) / 20.0;

                return Stack(children: [
                  TransformHelper.translateAndScale(
                      translateX: constraints.maxWidth * 0.04116222760290557,
                      translateY: constraints.maxHeight * 0.9279891304347826,
                      translateZ: 0,
                      scaleX: scaleX,
                      scaleY: scaleY,
                      scaleZ: 1,
                      child: GeneratedVectorWidget110())
                ]);
              }),
            ),
            Positioned(
              left: null,
              top: null,
              right: 0.0,
              bottom: null,
              width: 413.0,
              height: 30.0,
              child: TransformHelper.translate(
                  x: 0.00,
                  y: -264.00,
                  z: 0,
                  child: GeneratedRectangle29Widget()),
            ),
            Positioned(
              left: 0.0,
              top: 89.0,
              right: null,
              bottom: null,
              width: 415.0,
              height: 32.0,
              child: GeneratedFormadepagementoWidget(),
            ),
            Positioned(
              left: 0.0,
              top: 169.0,
              right: null,
              bottom: null,
              width: 413.0,
              height: 108.0,
              child: GeneratedRectangle30Widget(),
            ),
            Positioned(
              left: 0.0,
              top: 277.0,
              right: null,
              bottom: null,
              width: 413.0,
              height: 108.0,
              child: GeneratedRectangle31Widget(),
            ),
            Positioned(
              left: 55.0,
              top: 296.0,
              right: null,
              bottom: null,
              width: 72.0,
              height: 69.0,
              child: GeneratedEllipse6Widget(),
            ),
            Positioned(
              left: 55.0,
              top: 406.0,
              right: null,
              bottom: null,
              width: 72.0,
              height: 69.0,
              child: GeneratedEllipse7Widget(),
            ),
            Positioned(
              left: 53.0,
              top: 568.0,
              right: null,
              bottom: null,
              width: 74.0,
              height: 69.0,
              child: GeneratedEllipse8Widget(),
            ),
            Positioned(
              left: 56.0,
              top: 659.0,
              right: null,
              bottom: null,
              width: 71.0,
              height: 69.0,
              child: GeneratedEllipse9Widget(),
            ),
            Positioned(
              left: 4.0,
              top: 517.0,
              right: null,
              bottom: null,
              width: 415.0,
              height: 28.0,
              child: GeneratedOutrosmeiosdepagementoWidget(),
            ),
            Positioned(
              left: 55.0,
              top: 185.0,
              right: null,
              bottom: null,
              width: 72.0,
              height: 69.0,
              child: GeneratedEllipse5Widget(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                double percentWidth = 0.048426150121065374;
                double scaleX = (constraints.maxWidth * percentWidth) / 20.0;

                double percentHeight = 0.02717391304347826;
                double scaleY = (constraints.maxHeight * percentHeight) / 20.0;

                return Stack(children: [
                  TransformHelper.translateAndScale(
                      translateX: constraints.maxWidth * 0.043583535108958835,
                      translateY: constraints.maxHeight * 0.5815217391304348,
                      translateZ: 0,
                      scaleX: scaleX,
                      scaleY: scaleY,
                      scaleZ: 1,
                      child: GeneratedVectorWidget111())
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                double percentWidth = 0.048426150121065374;
                double scaleX = (constraints.maxWidth * percentWidth) / 20.0;

                double percentHeight = 0.02717391304347826;
                double scaleY = (constraints.maxHeight * percentHeight) / 20.0;

                return Stack(children: [
                  TransformHelper.translateAndScale(
                      translateX: constraints.maxWidth * 0.03631961259079903,
                      translateY: constraints.maxHeight * 0.43478260869565216,
                      translateZ: 0,
                      scaleX: scaleX,
                      scaleY: scaleY,
                      scaleZ: 1,
                      child: GeneratedVectorWidget112())
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                double percentWidth = 0.048426150121065374;
                double scaleX = (constraints.maxWidth * percentWidth) / 20.0;

                double percentHeight = 0.02717391304347826;
                double scaleY = (constraints.maxHeight * percentHeight) / 20.0;

                return Stack(children: [
                  TransformHelper.translateAndScale(
                      translateX: constraints.maxWidth * 0.03631961259079903,
                      translateY: constraints.maxHeight * 0.2758152173913043,
                      translateZ: 0,
                      scaleX: scaleX,
                      scaleY: scaleY,
                      scaleZ: 1,
                      child: GeneratedVectorWidget113())
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                double percentWidth = 0.11138014527845036;
                double scaleX = (constraints.maxWidth * percentWidth) / 46.0;

                double percentHeight = 0.043478260869565216;
                double scaleY = (constraints.maxHeight * percentHeight) / 32.0;

                return Stack(children: [
                  TransformHelper.translateAndScale(
                      translateX: constraints.maxWidth * 0.162227602905569,
                      translateY: constraints.maxHeight * 0.2758152173913043,
                      translateZ: 0,
                      scaleX: scaleX,
                      scaleY: scaleY,
                      scaleZ: 1,
                      child: GeneratedVectorWidget114())
                ]);
              }),
            ),
            Positioned(
              left: 131.0,
              top: 205.0,
              right: null,
              bottom: null,
              width: 283.0,
              height: 35.0,
              child: GeneratedDbitoWidget(),
            ),
            Positioned(
              left: 131.0,
              top: 313.0,
              right: null,
              bottom: null,
              width: 283.0,
              height: 32.0,
              child: GeneratedCrditoWidget(),
            ),
            Positioned(
              left: 131.0,
              top: 421.0,
              right: null,
              bottom: null,
              width: 284.0,
              height: 27.0,
              child: GeneratedNovocartoWidget(),
            ),
            Positioned(
              left: 256.0,
              top: 590.0,
              right: null,
              bottom: null,
              width: 33.0,
              height: 30.0,
              child: GeneratedPIXWidget(),
            ),
            Positioned(
              left: 131.0,
              top: 682.0,
              right: null,
              bottom: null,
              width: 288.0,
              height: 35.0,
              child: GeneratedBoletoWidget(),
            ),
            Positioned(
              left: 60.0,
              top: 305.0,
              right: null,
              bottom: null,
              width: 60.0,
              height: 52.0,
              child: GeneratedFrame8Widget(),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                double percentWidth = 0.09685230024213075;
                double scaleX = (constraints.maxWidth * percentWidth) / 40.0;

                double percentHeight = 0.043478260869565216;
                double scaleY = (constraints.maxHeight * percentHeight) / 32.0;

                return Stack(children: [
                  TransformHelper.translateAndScale(
                      translateX: constraints.maxWidth * 0.17191283292978207,
                      translateY: constraints.maxHeight * 0.5747282608695652,
                      translateZ: 0,
                      scaleX: scaleX,
                      scaleY: scaleY,
                      scaleZ: 1,
                      child: GeneratedVectorWidget116())
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                double percentWidth = 0.08716707021791767;
                double scaleX = (constraints.maxWidth * percentWidth) / 36.0;

                double percentHeight = 0.04891304347826087;
                double scaleY = (constraints.maxHeight * percentHeight) / 36.0;

                return Stack(children: [
                  TransformHelper.translateAndScale(
                      translateX: constraints.maxWidth * 0.17675544794188863,
                      translateY: constraints.maxHeight * 0.7948369565217391,
                      translateZ: 0,
                      scaleX: scaleX,
                      scaleY: scaleY,
                      scaleZ: 1,
                      child: GeneratedVectorWidget117())
                ]);
              }),
            ),
            Positioned(
              left: 0.0,
              top: 0.0,
              right: 0.0,
              bottom: 0.0,
              width: null,
              height: null,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                double percentWidth = 0.06779661016949153;
                double scaleX = (constraints.maxWidth * percentWidth) / 28.0;

                double percentHeight = 0.021739130434782608;
                double scaleY = (constraints.maxHeight * percentHeight) / 16.0;

                return Stack(children: [
                  TransformHelper.translateAndScale(
                      translateX: constraints.maxWidth * 0.18886198547215496,
                      translateY: constraints.maxHeight * 0.9320652173913043,
                      translateZ: 0,
                      scaleX: scaleX,
                      scaleY: scaleY,
                      scaleZ: 1,
                      child: GeneratedVectorWidget118())
                ]);
              }),
            )
          ]),
    ));
  }
}
